import React,{useState, useEffect} from 'react';
import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import Footer from "../components/footer";
import SkillsComponent from "../components/skills";
import { FaGithub, FaTwitter, FaLinkedin } from "react-icons/fa";
import Button from '../components/button';

export default function Home() {
  const { systemTheme, theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);
  const renderThemeChanger = () => {
    if(!mounted) return null;

    const currentTheme = theme === 'system' ? systemTheme : theme;
    
    if(currentTheme === 'dark') {
      return (
        <Button className="bg-gradient-to-r  from-cyan-500 to-teal-500"
          onClick={() => setTheme('light')}
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clipRule="evenodd" />
          </svg>
        </Button>
      )
    } else {
      return (
        <Button className="bg-gradient-to-r  from-cyan-500 to-teal-500"
          onClick={() => setTheme('dark')}
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
          </svg>
        </Button>
      )
    }

  }
  return (
    <>
      <Head>
        <title>Bharat Gupta Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developed by</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className=" hover:ring-2 hover:ring-gray-300 bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="../public/bharatguptaresume.pdf"
                  download="Bharat Gupta resume"
                  target="_blank"
                >
                  Resume
                </a>    
                </li>
                <li className='pl-5 '>
                {renderThemeChanger()}
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Bharat Gupta
            </h2>
            <h3 className="text-2xl py-2 md:text-xl"> Software Developer</h3>
            <p className="text-gray-600">
              {" "}
              I'm a graduate student of CSUSB class of 22 and my passion is
              Computer Science. <br />
              My interset includes developing new software, frontend, backend,
              designing.
            </p>
            <div className="flex justify-center gap-6 p-5">
              <a
                className="cursor-pointer"
                href="https://twitter.com/bharatgupta07"
                target="_blank"
              >
                <FaTwitter className="text-2xl cursor-pointer hover:text-blue-600" />
              </a>
              <a
                className="cursor-pointer"
                href="https://www.linkedin.com/in/bharat-gupta-07/"
                target="_blank"
              >
                <FaLinkedin className="text-2xl cursor-pointer hover:text-blue-600" />
              </a>
              <a
                className="cursor-pointer"
                href="https://github.com/virat07"
                target="_blank"
              >
                <FaGithub className="text-2xl cursor-pointer hover:text-gray-600" />
              </a>
            </div>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} alt="dev" layout="fill" objectFit="cover" />
          </div>
        </section>
        <div></div>
        <SkillsComponent />
      </main>
      <Footer />
    </>
  );
}
